### ISSUE TITLE
Allow adjusting or removing redirect delay

### ISSUE THREAD

**Issue by Nothing4You** [RikudouSage/lemmyverse.link#3]
It would be nice to have the option to skip the redirect delay.

It would likely be necessary to add a way to configure this setting from the main page to prevent users from locking in this setting and not being able to disable it anymore.

Additionally, when adding settings on the main page, that could be an opportunity to add configuring the home instance there.

**Comment by RikudouSage** [comment]
It's done, when set to 0, it entirely skips rendering the HTML page and does a http redirect directly. I don't have much time, so the UX is suboptimal, but it's not something people will interact with often.
